export enum ErrorCode {
  // Tenant Errors
  TENANT_ID_REQUIRED = 'TENANT_ID_REQUIRED',
  TENANT_ID_INVALID = 'TENANT_ID_INVALID',
  TENANT_ACCESS_DENIED = 'TENANT_ACCESS_DENIED',
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  TENANT_INACTIVE = 'TENANT_INACTIVE',
  TENANT_LINE_NOT_CONFIGURED = 'TENANT_LINE_NOT_CONFIGURED',

  // Auth Errors
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  AUTH_INVALID = 'AUTH_INVALID',
  AUTH_USER_NOT_LINKED = 'AUTH_USER_NOT_LINKED',
  AUTH_PROVIDER_UNAVAILABLE = 'AUTH_PROVIDER_UNAVAILABLE',

  // Resource & Service Errors
  SERVICE_NOT_FOUND = 'SERVICE_NOT_FOUND',
  SERVICE_INACTIVE = 'SERVICE_INACTIVE',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

  // Staff Errors
  STAFF_NOT_FOUND = 'STAFF_NOT_FOUND',
  STAFF_NOT_ELIGIBLE = 'STAFF_NOT_ELIGIBLE',
  STAFF_NOT_AVAILABLE = 'STAFF_NOT_AVAILABLE',
  STAFF_SELECTION_DISABLED = 'STAFF_SELECTION_DISABLED',

  // Customer Errors
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',

  // Booking Domain & Availability Errors
  BOOKING_IN_PAST = 'BOOKING_IN_PAST',
  BOOKING_TOO_SOON = 'BOOKING_TOO_SOON',
  BOOKING_TOO_FAR_AHEAD = 'BOOKING_TOO_FAR_AHEAD',
  BOOKING_OUTSIDE_BUSINESS_HOURS = 'BOOKING_OUTSIDE_BUSINESS_HOURS',
  BOOKING_SLOT_UNAVAILABLE = 'BOOKING_SLOT_UNAVAILABLE',
  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  INVALID_BOOKING_STATUS = 'INVALID_BOOKING_STATUS',

  // Generic Fallback Errors
  BAD_REQUEST = 'BAD_REQUEST',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
